# Generated by Django 5.1.2 on 2024-10-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_subject_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_url',
            field=models.URLField(null=True),
        ),
    ]
