# Generated by Django 5.1.2 on 2024-10-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subject_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course_url',
        ),
    ]
